name: ProfCalendarParents
options:
  bundleIdPrefix: ch.teacherplanner
  deploymentTarget:
    iOS: "15.0"
targets:
  ProfCalendarParents:
    type: application
    platform: iOS
    sources:
      - ProfCalendarParents
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ch.teacherplanner.parents
      INFOPLIST_FILE: ProfCalendarParents/Info.plist
      TARGETED_DEVICE_FAMILY: "1"
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "267P8NFWYA"
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
