"""Add decoupage models

Revision ID: 3894eb851cd3
Revises: 20260124_add_blank_sheets
Create Date: 2026-02-07 13:41:02.569572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3894eb851cd3'
down_revision = '20260124_add_blank_sheets'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decoupages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decoupage_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoupage_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['decoupage_id'], ['decoupages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decoupage_id', 'classroom_id', name='_decoupage_classroom_uc')
    )
    op.create_table('decoupage_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoupage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decoupage_id'], ['decoupages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_blank_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_blank_sheets_lesson_date'))
        batch_op.drop_index(batch_op.f('idx_blank_sheets_period_number'))
        batch_op.drop_index(batch_op.f('idx_blank_sheets_user_date_period'))
        batch_op.create_index(batch_op.f('ix_lesson_blank_sheets_lesson_date'), ['lesson_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_blank_sheets_period_number'), ['period_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_blank_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_blank_sheets_period_number'))
        batch_op.drop_index(batch_op.f('ix_lesson_blank_sheets_lesson_date'))
        batch_op.create_index(batch_op.f('idx_blank_sheets_user_date_period'), ['user_id', 'lesson_date', 'period_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_blank_sheets_period_number'), ['period_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_blank_sheets_lesson_date'), ['lesson_date'], unique=False)

    op.drop_table('decoupage_periods')
    op.drop_table('decoupage_assignments')
    op.drop_table('decoupages')
    # ### end Alembic commands ###
